---
- name: Check prerequisite.
  import_tasks: check_prerequisite.yml

# Replace PI user
- name: Replace Pi user by {{ rasp_user }}.
  import_tasks: replace_pi_user.yml

# SSH config
- name: ssh.
  import_tasks: ssh.yml

- meta: flush_handlers

# Interfacing options
- name: camera.
  import_tasks: interfacing_options/camera.yml

- name: i2c.
  import_tasks: interfacing_options/i2c.yml

- name: onewire.
  import_tasks: interfacing_options/onewire.yml

- name: remote GPIO.
  import_tasks: interfacing_options/remote_gpio.yml

- name: serial.
  import_tasks: interfacing_options/serial.yml

- name: spi.
  import_tasks: interfacing_options/spi.yml

- name: vnc.
  import_tasks: interfacing_options/vnc.yml

# Packages
- name: Install packages.
  import_tasks: packages.yml

# Fail2ban.conf
- name: Configure Fail2ban.
  import_tasks: fail2ban.yml

# Firewall
- name: Set Firewall.
  import_tasks: ufw.yml

## Reboot
- name: Reboot.
  import_tasks: reboot.yml
